/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/deployer
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import type { DeployContext } from '../context.js';

export function generateCaddy(ctx: DeployContext): string {
  const caddyAddress = ctx.hostname || ':80';
  const spaCaddyLine = ctx.isSpa
    ? '    try_files {path} {path}/ /index.html'
    : '    try_files {path} {path}/';

  return `# ---------------------------------------------------
# Caddyfile generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/caddy
# ---------------------------------------------------

${caddyAddress} {
    root * ./${ctx.outDir}
    file_server

    # SPA Routing Fallback
${spaCaddyLine}

    # Security headers
    header {
        X-Content-Type-Options   "nosniff"
        X-Frame-Options          "SAMEORIGIN"
        X-XSS-Protection         "1; mode=block"
        Referrer-Policy          "strict-origin-when-cross-origin"
        Permissions-Policy       "camera=(), microphone=(), geolocation=()"
        # HSTS (1 year). Only enable after verifying HTTPS works end-to-end.
        # Strict-Transport-Security "max-age=31536000; includeSubDomains"
        # CSP — adjust if you embed third-party widgets or analytics.
        Content-Security-Policy  "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'self'"
        -Server
    }

    # Custom 404
    handle_errors {
        rewrite * /404.html
        file_server
    }

    # Cache Static Assets (6 months)
    @static {
        file
        path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.webp *.avif *.svg *.woff *.woff2 *.eot *.ttf *.otf
    }
    header @static Cache-Control "public, max-age=15552000, immutable"
}
`;
}