/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/deployer
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import type { DeployContext } from '../context.js';

export async function generateDocker(ctx: DeployContext): Promise<{ dockerfile: string; dockerignore: string }> {
  const buildCmd = ctx.configFile ? `docmd build --config ${ctx.configFile}` : 'docmd build';

  const dockerfile = `# ---------------------------------------------------
# Dockerfile generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/docker
# ---------------------------------------------------

# Stage 1: Build the docmd site
FROM node:22-alpine AS builder
WORKDIR /app

# Copy dependency manifests first for optimal layer caching
COPY package*.json ./
RUN if [ -f package.json ]; then npm install --ignore-scripts; fi

# Copy the rest of the project
COPY . .

# Install the exact docmd core version used to configure this deployment
RUN npm install -g @docmd/core@${ctx.version}

# Build the site
RUN ${buildCmd}

# Stage 2: Serve with nginx
FROM nginx:alpine
COPY --from=builder /app/${ctx.outDir} /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;

  const dockerignore = `node_modules
${ctx.outDir}
dist
.git
.gitignore
.env
.env.*
*.md
!docs/**/*.md
.DS_Store
Thumbs.db
`;

  return { dockerfile, dockerignore };
}