/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/deployer
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import type { DeployContext } from '../context.js';

export function generateNetlify(ctx: DeployContext): string {
  // T-Z9: do NOT emit a `[[redirects]] from = "/*" status = 200` block.
  // docmd generates real HTML files for every route (SPA mode is a thin
  // client-side layer on top of pre-rendered HTML, not a single-page
  // app served from /). A catch-all to /index.html with status 200
  // makes missing routes return 200 with the home page content — a
  // soft-404 that hides errors, hurts SEO, and creates a URL
  // enumeration surface. Without the redirect, Netlify serves the
  // generated file if it exists, or the bundled 404.html (with 404
  // status) if not.
  return `# ---------------------------------------------------
# netlify.toml generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/netlify
# ---------------------------------------------------

[build]
  command = "npm install -g @docmd/core@${ctx.version} && docmd build"
  publish = "${ctx.outDir}"

[build.environment]
  NODE_VERSION = "20"

# Security headers applied to every response.
# HSTS is commented out — enable it after verifying HTTPS works end-to-end.
# CSP: adjust default-src if you embed third-party widgets or analytics.
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options  = "nosniff"
    X-Frame-Options         = "SAMEORIGIN"
    X-XSS-Protection        = "1; mode=block"
    Referrer-Policy         = "strict-origin-when-cross-origin"
    Permissions-Policy      = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'self'"
    # Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=15552000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
`;
}