/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/deployer
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import type { DeployContext } from '../context.js';

export function generateNginx(ctx: DeployContext): string {
  const serverName = ctx.hostname || 'localhost';
  const spaBlock = ctx.isSpa ? `
    # SPA Routing Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }
` : `
    location / {
        try_files $uri $uri/ =404;
    }
`;

  return `# ---------------------------------------------------
# nginx.conf generated by docmd v${ctx.version}
# Project: ${ctx.title}
# https://docmd.io/deployment/nginx
# ---------------------------------------------------

server {
    listen 80;
    server_name ${serverName};
    root /usr/share/nginx/html;
    index index.html;

    # Security headers
    server_tokens off;
    add_header X-Content-Type-Options   "nosniff"                          always;
    add_header X-Frame-Options          "SAMEORIGIN"                       always;
    add_header X-XSS-Protection         "1; mode=block"                    always;
    add_header Referrer-Policy          "strict-origin-when-cross-origin"  always;
    add_header Permissions-Policy       "camera=(), microphone=(), geolocation=()" always;
    # HSTS (1 year). Only enable after verifying HTTPS works end-to-end.
    # add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    # CSP — adjust 'default-src' if you embed third-party widgets or analytics.
    add_header Content-Security-Policy  "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self'; frame-ancestors 'self'" always;

    # GZIP Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;
${spaBlock}
    # Custom 404
    error_page 404 /404.html;

    # Cache Control for Static Assets
    location ~* \\.(?:ico|css|js|gif|jpe?g|png|webp|avif|woff2?|eot|ttf|otf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}
`;
}