/**
 * --------------------------------------------------------------------
 * docmd : the zero-config documentation engine.
 *
 * @package     @docmd/core (and ecosystem)
 * @website     https://docmd.io
 * @repository  https://github.com/docmd-io/docmd
 * @license     MIT
 * @copyright   Copyright (c) 2025-present docmd.io
 *
 * [docmd-source] - Please do not remove this header.
 * --------------------------------------------------------------------
 */

import fs from 'node:fs/promises';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { exists } from '../utils/fs-utils.js';
import pc from 'chalk';

// Use synchronous read to avoid top-level await fragility
const pkgUrl = new URL('../../package.json', import.meta.url);
const { version } = JSON.parse(readFileSync(pkgUrl, 'utf-8'));

interface DeployOpts {
  docker?: boolean;
  nginx?: boolean;
  caddy?: boolean;
  force?: boolean;
}

/**
 * Safely writes a deployment file. Skips if it exists (unless --force).
 * Returns true if the file was written.
 */
async function writeDeployFile(filePath: string, content: string, label: string, force: boolean): Promise<boolean> {
  if (!force && (await exists(filePath))) {
    console.log(`  ${pc.yellow('⚠')} ${label} already exists, skipping. Use ${pc.cyan('--force')} to overwrite.`);
    return false;
  }
  await fs.writeFile(filePath, content, 'utf8');
  console.log(`  ${pc.green('✓')} Generated ${label}`);
  return true;
}

export async function generateDeployConfigs(opts: DeployOpts) {
  const cwd = process.cwd();
  const force = opts.force || false;
  let generatedCount = 0;

  if (opts.docker) {
    // Check if user also generated nginx.conf — if so, copy it into the container
    const hasNginxConf = opts.nginx || (await exists(resolve(cwd, 'nginx.conf')));
    const nginxCopyLine = hasNginxConf
      ? 'COPY nginx.conf /etc/nginx/conf.d/default.conf'
      : '';

    const dockerfile = `# ---------------------------------------------------
# Dockerfile generated by docmd v${version}
# https://docmd.io/deployment/docker
# ---------------------------------------------------

# Stage 1: Build the docmd site
FROM node:20-alpine AS builder
WORKDIR /app

# Copy dependency manifests first for optimal layer caching
COPY package*.json ./
RUN if [ -f package.json ]; then npm install --ignore-scripts; fi

# Copy the rest of the project
COPY . .

# Install the exact docmd core version used to configure this deployment
RUN npm install -g @docmd/core@${version}

# Build the site
RUN docmd build

# Stage 2: Serve with nginx
FROM nginx:alpine
${nginxCopyLine}
COPY --from=builder /app/site /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;

    const dockerignore = `node_modules
site
dist
.git
.gitignore
.env
.env.*
*.md
!docs/**/*.md
.DS_Store
Thumbs.db
`;

    if (await writeDeployFile(resolve(cwd, 'Dockerfile'), dockerfile, 'Dockerfile', force)) generatedCount++;
    if (await writeDeployFile(resolve(cwd, '.dockerignore'), dockerignore, '.dockerignore', force)) generatedCount++;
  }

  if (opts.nginx) {
    const nginxConf = `# ---------------------------------------------------
# nginx.conf generated by docmd v${version}
# https://docmd.io/deployment/nginx
# ---------------------------------------------------

server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # Security
    server_tokens off;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;

    # GZIP Compression
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_min_length 256;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        text/xml
        application/xml
        application/xml+rss
        text/javascript
        image/svg+xml;

    # SPA Routing Fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Custom 404
    error_page 404 /404.html;

    # Cache Control for Static Assets
    location ~* \\.(?:ico|css|js|gif|jpe?g|png|webp|avif|woff2?|eot|ttf|otf|svg)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}
`;
    if (await writeDeployFile(resolve(cwd, 'nginx.conf'), nginxConf, 'nginx.conf', force)) generatedCount++;
  }

  if (opts.caddy) {
    const caddyfile = `# ---------------------------------------------------
# Caddyfile generated by docmd v${version}
# https://docmd.io/deployment/caddy
# ---------------------------------------------------

:80 {
    root * ./site
    file_server

    # SPA Routing Fallback
    try_files {path} {path}/ /index.html

    # Security Headers
    header {
        X-Content-Type-Options "nosniff"
        X-Frame-Options "SAMEORIGIN"
        -Server
    }

    # Custom 404
    handle_errors {
        rewrite * /404.html
        file_server
    }

    # Cache Static Assets (6 months)
    @static {
        file
        path *.ico *.css *.js *.gif *.jpg *.jpeg *.png *.webp *.avif *.svg *.woff *.woff2 *.eot *.ttf *.otf
    }
    header @static Cache-Control "public, max-age=15552000, immutable"
}
`;
    if (await writeDeployFile(resolve(cwd, 'Caddyfile'), caddyfile, 'Caddyfile', force)) generatedCount++;
  }

  if (generatedCount === 0 && (opts.docker || opts.nginx || opts.caddy)) {
    console.log(`  ${pc.blue('ℹ')} No new deployment files generated. All targets already exist.`);
  }
}